-libraryjars /opt/WTK2.5.2/lib/mmapi.jar:/opt/WTK2.5.2/lib/midpapi21.jar:/opt/WTK2.5.2/lib/cldcapi11.jar
-injars /home/d6556/j2mewtk/2.5.2/apps/HelicopterGame/bin/HelicopterGame.jar
-outjar /tmp/HelicopterGame.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
